### ISSUE TITLE
Pcb holes 

### ISSUE THREAD

**Issue by GeneralMidi** [tomsaleeba/ergoslab#2]
Hi, I'm very interested in trying your build, but thought I would try the ergodox first. I uploaded the Gerber files to jlcpcb and I got en email back saying the holes are the same size as the pads. As a complete noob, I thought I'd ask you! Is it really as simple as "use alternate drill mode"? 
Cheers
Luke

**Comment by GeneralMidi** [comment]
All good. Apparently it's fine

**Comment by tomsaleeba** [comment]
Hi @GeneralMidi , I'm excited you're giving my keyboard a try. Did you use the gerbers from the releases page here on GitHub or generate them yourself? As I mention on the release for v1.0.0, I haven't had them manufactured so if there's something wrong with the gerbers, I'm eager to get the problem fixed.

**Comment by GeneralMidi** [comment]
Nah mate, it was for the ergodox. See here:

https://www.reddit.com/r/ergodox/comments/en8al2/jlcpcb_issue_with_drill_holes/
